Regions:
  Name1:
    World:
    Loc1:
      X:
      Y:
      Z:
    Loc2:
      X:
      Y:
      Z:
Messages:
  Warnings:
    PositionSet: "&aPosition set successfully. Dont forget to use &f/killondisconnect reload"
    Reloaded: "&aConfig was reloaded successfully"
  Errors:
    NotAllowed: "&cNot allowed"
    WrongIndex: "&cIndex must be 1 or 2"
    MustBePlayer: "&cOnly players can execute this command"
  Usage:
    SetPosition: "&eUsage: /KillOnDisconnect set <name> <index:1/2>"
    Reload: "&eUsage: /KillOnDisconnect reload"